---
name: PITA-Test-Dummy-Perl5-Build
version: 1.00
author:
  - Adam Kennedy <cpan@ali.as>
abstract: ~
license: perl
provides:
  PITA::Test::Dummy::Perl5::Build:
    file: lib/PITA/Test/Dummy/Perl5/Build.pm
    version: 1.00
generated_by: Module::Build version 0.2611
